services:
  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - pismo
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: payment
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      # - ./db:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 5432:5432
    networks:
      - pismo
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payment
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - pismo
      
networks:
  pismo:
    driver: bridge